plugins:
  - react
  - jasmine
env:
  browser: true
  es6: true
  node: true
  jasmine: true
extends:
  - airbnb
  - 'plugin:jasmine/recommended'
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module

rules: { semi: 2 }
